package eu.kanade.tachiyomi.extension.vi.cuutruyen

import android.R.attr.name
import eu.kanade.tachiyomi.source.model.Filter

class TagFilter(tags: List<Tag>) :
    Filter.Group<Tag>(
        "Thể loại",
        tags,
    )

class Tag(name: String, val id: String) : Filter.CheckBox(name) {
    override fun toString(): String = name
}

// Got this list off their Discord, they don't have a tag list on the website
fun tagList() = listOf(
    Tag("Action", "action"),
    Tag("Adaption", "adaption"),
    Tag("Adventure", "adventure"),
    Tag("Aliens", "aliens"),
    Tag("Animals", "animals"),
    Tag("Anime", "anime"),
    Tag("Atlus", "atlus"),
    Tag("Award winning", "award winning"),
    Tag("Ẩm thực", "ẩm thực"),
    Tag("Bạo lực", "bạo lực"),
    Tag("Bi kịch", "bi kịch"),
    Tag("Bí ẩn", "bí ẩn"),
    Tag("Cảnh sát", "cảnh sát"),
    Tag("Chất lượng cao", "chất lượng cao"),
    Tag("Chính kịch", "chính kịch"),
    Tag("Chính trị", "chính trị"),
    Tag("Chuyển sinh", "chuyển sinh"),
    Tag("Chuyển thể", "chuyển thể"),
    Tag("Comedy", "comedy"),
    Tag("Công sở", "công sở"),
    Tag("Cooking", "cooking"),
    Tag("Có màu", "có màu"),
    Tag("Dark fantasy", "dark fantasy"),
    Tag("Databook", "databook"),
    Tag("Doujinshi", "doujinshi"),
    Tag("Drama", "drama"),
    Tag("Du hành thời gian", "du hành thời gian"),
    Tag("Đã hoàn thành", "đã hoàn thành"),
    Tag("Đang tiến hành", "đang tiến hành"),
    Tag("Địa chính trị", "địa chính trị"),
    Tag("Đời thường", "đời thường"),
    Tag("Động vật", "động vật"),
    Tag("Ecchi", "ecchi"),
    Tag("Fantasy", "fantasy"),
    Tag("Game", "game"),
    Tag("Ghosts", "ghosts"),
    Tag("Giật gân", "giật gân"),
    Tag("Gore", "gore"),
    Tag("Hài hước", "hài hước"),
    Tag("Hành động", "hành động"),
    Tag("Harem", "harem"),
    Tag("Hậu tận thế", "hậu tận thế"),
    Tag("Historical", "historical"),
    Tag("Học đường", "học đường"),
    Tag("Horror", "horror"),
    Tag("Idol", "idol"),
    Tag("Isekai", "isekai"),
    Tag("Josei", "josei"),
    Tag("Khoa học", "khoa học"),
    Tag("Khoa học viễn tưởng", "khoa học viễn tưởng"),
    Tag("Khoả thân", "khoả thân"),
    Tag("Kinh dị", "kinh dị"),
    Tag("Lãng mạn", "lãng mạn"),
    Tag("Lgbt", "lgbt"),
    Tag("Lịch sử", "lịch sử"),
    Tag("Manga", "manga"),
    Tag("Manhua", "manhua"),
    Tag("Manhwa", "manhwa"),
    Tag("Martial arts", "martial arts"),
    Tag("Máu me", "máu me"),
    Tag("Mecha", "mecha"),
    Tag("Medical", "medical"),
    Tag("Military", "military"),
    Tag("Miễn bản quyền", "miễn bản quyền"),
    Tag("Monsters", "monsters"),
    Tag("Monster girls", "monster girls"),
    Tag("Mystery", "mystery"),
    Tag("Nam biến nữ", "nam biến nữ"),
    Tag("Nam giả nữ", "nam giả nữ"),
    Tag("Nam x nam", "nam x nam"),
    Tag("Ngọt ngào", "ngọt ngào"),
    Tag("Ninja", "ninja"),
    Tag("Nsfw", "nsfw"),
    Tag("Ntr", "ntr"),
    Tag("Nữ giả nam", "nữ giả nam"),
    Tag("Oneshot", "oneshot"),
    Tag("Phép thuật", "phép thuật"),
    Tag("Phiêu lưu", "phiêu lưu"),
    Tag("Psychological", "psychological"),
    Tag("Quái vật", "quái vật"),
    Tag("Quân đội", "quân đội"),
    Tag("Romance", "romance"),
    Tag("Romcom", "romcom"),
    Tag("Rpg", "rpg"),
    Tag("Samurai", "samurai"),
    Tag("Sát thủ", "sát thủ"),
    Tag("School life", "school life"),
    Tag("Sci-fi", "sci fi"),
    Tag("Sega", "sega"),
    Tag("Seinen", "seinen"),
    Tag("Shoujo", "shoujo"),
    Tag("Shounen", "shounen"),
    Tag("Siêu nhiên", "siêu nhiên"),
    Tag("Sinh tồn", "sinh tồn"),
    Tag("Slice of life", "slice of life"),
    Tag("Smut", "smut"),
    Tag("Sport", "sport"),
    Tag("Supernatural", "supernatural"),
    Tag("Survival", "survival"),
    Tag("Tạm ngưng", "tạm ngưng"),
    Tag("Tâm lý", "tâm lý"),
    Tag("Thể thao", "thể thao"),
    Tag("Thiếu niên", "thiếu niên"),
    Tag("Thriller", "thriller"),
    Tag("Tình dục", "tình dục"),
    Tag("Tình yêu", "tình yêu"),
    Tag("Tình yêu không được đáp lại", "tình yêu không được đáp lại"),
    Tag("Tình yêu thuần khiết", "tình yêu thuần khiết"),
    Tag("Toán học", "toán học"),
    Tag("Tội phạm", "tội phạm"),
    Tag("Tragedy", "tragedy"),
    Tag("Trinh thám", "trinh thám"),
    Tag("Trung cổ", "trung cổ"),
    Tag("Tu tiên", "tu tiên"),
    Tag("Tuyển tập", "tuyển tập"),
    Tag("Vampires", "vampires"),
    Tag("Video games", "video games"),
    Tag("Việt nam", "việt nam"),
    Tag("Virtual reality", "virtual reality"),
    Tag("Võ thuật", "võ thuật"),
    Tag("Vô cp", "vô cp"),
    Tag("Web comic", "web comic"),
    Tag("Webtoon", "webtoon"),
    Tag("Wholesome", "wholesome"),
    Tag("Xuyên không", "xuyên không"),
    Tag("Y học", "y học"),
    Tag("Yaoi", "yaoi"),
    Tag("Yakuza", "yakuza"),
    Tag("Yonkoma", "yonkoma"),
    Tag("Yuri", "yuri"),
    Tag("Zombie", "zombie"),
)
