package eu.kanade.tachiyomi.extension.vi.cuutruyencc

import eu.kanade.tachiyomi.source.model.Filter

class Genre(name: String, val id: String = name) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

fun getGenreList() = listOf(
    Genre("Action"),
    Genre("Adult"),
    Genre("Adventure"),
    Genre("Anime"),
    Genre("Chuyển Sinh"),
    Genre("Comedy"),
    Genre("Comic"),
    Genre("Cooking"),
    Genre("Cổ Đại"),
    Genre("Doujinshi"),
    Genre("Drama"),
    Genre("Ecchi"),
    Genre("Fantasy"),
    Genre("Gender Bender"),
    Genre("Harem"),
    Genre("Historical"),
    Genre("Horror"),
    Genre("Josei"),
    Genre("Live action"),
    Genre("Manga"),
    Genre("Manhua"),
    Genre("Manhwa"),
    Genre("Martial Arts"),
    Genre("Mature"),
    Genre("Mecha"),
    Genre("Mystery"),
    Genre("Ngôn Tình"),
    Genre("One shot"),
    Genre("Psychological"),
    Genre("Romance"),
    Genre("School Life"),
    Genre("Sci-fi"),
    Genre("Seinen"),
    Genre("Shoujo"),
    Genre("Shoujo Ai"),
    Genre("Shounen"),
    Genre("Shounen Ai"),
    Genre("Slice of Life"),
    Genre("Smut"),
    Genre("Soft Yaoi"),
    Genre("Soft Yuri"),
    Genre("Sports"),
    Genre("Supernatural"),
    Genre("Tạp chí truyện tranh"),
    Genre("Thiếu Nhi"),
    Genre("Tragedy"),
    Genre("Trinh Thám"),
    Genre("Truyện scan"),
    Genre("Truyện Màu"),
    Genre("Việt Nam"),
    Genre("Webtoon"),
    Genre("Xuyên Không"),
    Genre("16+"),
    Genre("Tạm ngưng"),
    Genre("Đang tiến hành"),
    Genre("Đã hoàn thành"),
    Genre("Romcom"),
    Genre("Oneshot"),
    Genre("Thriller"),
    Genre("Award Winning"),
    Genre("Reincarnation"),
    Genre("Sci-Fi"),
    Genre("Time Travel"),
    Genre("Genderswap"),
    Genre("Loli"),
    Genre("Traditional Games"),
    Genre("Official Colored"),
    Genre("Monsters"),
    Genre("Demons"),
    Genre("Ghosts"),
    Genre("Animals"),
    Genre("Long Strip"),
    Genre("Ninja"),
    Genre("Anthology"),
    Genre("Boys' Love"),
    Genre("Incest"),
    Genre("Crime"),
    Genre("Survival"),
    Genre("Zombies"),
    Genre("Reverse Harem"),
    Genre("Superhero"),
    Genre("Fan Colored"),
    Genre("Samurai"),
    Genre("Magical Girls"),
    Genre("Mafia"),
    Genre("Self-Published"),
    Genre("Virtual Reality"),
    Genre("Office Workers"),
    Genre("Video Games"),
    Genre("Post-Apocalyptic"),
    Genre("Sexual Violence"),
    Genre("Crossdressing"),
    Genre("Magic"),
    Genre("Girls' Love"),
    Genre("Military"),
    Genre("Wuxia"),
    Genre("Isekai"),
    Genre("4-Koma"),
    Genre("Philosophical"),
    Genre("Gore"),
    Genre("Medical"),
    Genre("Villainess"),
    Genre("Vampires"),
    Genre("Delinquents"),
    Genre("Monster Girls"),
    Genre("Shota"),
    Genre("Police"),
    Genre("Web Comic"),
    Genre("Aliens"),
    Genre("Adaptation"),
    Genre("Music"),
    Genre("Full Color"),
    Genre("Gyaru"),
)
